changes in new_rental, gui and databasehelper
error: in case of panel change values were not deleted in new_rental --> solved, now values are deleted,
completed my database methods with user input --> changed the methodos to methods using prepared statement